@url = http://localhost:8080/api/agency/agent
@token = eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJidWctc2FmYXJpIiwic3ViIjoiam9obkBzbWl0aC5jb20iLCJhdXRob3JpdGllcyI6IlJPTEVfQURNSU4iLCJleHAiOjE2Mzk3MTQ4OTZ9.SBDSFXdO8UkGsL7lKkQNU0cgBNdUkgRQjBF8GodI52M

POST {{url}} HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "agencyId": 1,
    "identifier": "007",
    "activationDate": "2010-04-04",
    "securityClearance": {
        "securityClearanceId": 1
    },
    "agent": {
        "agentId": 2
    }
}

###

PUT {{url}} HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "agencyId": 1,
    "identifier": "agent x",
    "activationDate": "2010-04-04",
    "securityClearance": {
        "securityClearanceId": 1
    },
    "agent": {
        "agentId": 1
    }
}

###

DELETE {{url}}/1/1 HTTP/1.1
Authorization: Bearer {{token}}
